name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Modelo-Vino-Lambda

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read configuration file
        id: read-config
        run: |
          config=$(cat workflowfile.json)
          echo "::set-output name=region::$(echo $config | jq -r .environment.region)"
          echo "::set-output name=bucket_name::$(echo $config | jq -r .environment.bucket_name)"
          echo "::set-output name=lambda_function_name::$(echo $config | jq -r .environment.lambda_function_name)"
          echo "::set-output name=s3_key::$(echo $config | jq -r .environment.s3_key)"

      - name: Deploy to AWS Lambda
        uses: qubitro/action-lambda-python-zip@v1.0
        with:
          lambda_function_name: ${{ steps.read-config.outputs.lambda_function_name }}
          lambda_region: ${{ steps.read-config.outputs.region }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
